{"name": "作业发布", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'fail' == 'pass'", "trace": "self = <test_case.test_excel.TestExcel object at 0x000001645A702898>\nresult = {'data': {'action': 'add_task', 'desc': '30', 'examid': '9906', 'questionlist': '[[\"choice\",[{\"level\":1,\"id\":80852,\"requireprocess\":false}]],[]]', ...}, 'method': 'POST', 'res': <Response [200]>, 'result': 'fail', ...}\n\n    @allure.severity(allure.severity_level.CRITICAL)  # 发生BUG时的严重程度\n    @pytest.mark.parametrize(\"result\", results)\n    def test_excel(self, result):\n        allure.dynamic.title(str(result['title']))\n        allure.dynamic.description(f\"{str(result['method'])} {str(result['url'])}\")\n        with allure.step(f\"method:{str(result['method'])}\"):\n            pass\n        with allure.step(f\"url:{str(result['url'])}\"):\n            pass\n        with allure.step(f\"data:{str(result['data'])}\"):\n            pass\n        with allure.step(f\"res:{str(result['res'].json())}\"):\n            pass\n>       assert result[\"result\"] == \"pass\"\nE       AssertionError: assert 'fail' == 'pass'\n\ntest_excel.py:35: AssertionError"}, "description": "POST http://njqa.zgyjyx.net/api/teacher/mobile/general_task/", "steps": [{"name": "method:POST", "status": "passed", "start": 1609656972672, "stop": 1609656972672}, {"name": "url:http://njqa.zgyjyx.net/api/teacher/mobile/general_task/", "status": "passed", "start": 1609656972672, "stop": 1609656972672}, {"name": "data:{'action': 'add_task', 'recipients': '[[\"36301\",\"测试\"]]', 'examid': '9906', 'desc': '30', 'tasktype': 'exam', 'suggestspendtime': '30', 'questionlist': '[[\"choice\",[{\"level\":1,\"id\":80852,\"requireprocess\":false}]],[]]', 'subjectid': '1'}", "status": "passed", "start": 1609656972672, "stop": 1609656972672}, {"name": "res:{'retcode': 99, 'msg': '未登录'}", "status": "passed", "start": 1609656972672, "stop": 1609656972672}], "parameters": [{"name": "result", "value": "{'title': '作业发布', 'method': 'POST', 'url': 'http://njqa.zgyjyx.net/api/teacher/mobile/general_task/', 'data': {'action': 'add_task', 'recipients': '[[\"36301\",\"测试\"]]', 'examid': '9906', 'desc': '30', 'tasktype': 'exam', 'suggestspendtime': '30', 'questionlist': '[[\"choice\",[{\"level\":1,\"id\":80852,\"requireprocess\":false}]],[]]', 'subjectid': '1'}, 'result': 'fail', 'res': <Response [200]>}"}], "start": 1609656972672, "stop": 1609656972672, "uuid": "7aaccfe4-90e4-4617-9ce0-b175f64d420b", "historyId": "429b30e57c1644c4db7c130014850d89", "testCaseId": "c702837ae51103cc760768369bdfeabd", "fullName": "test_case.test_excel.TestExcel#test_excel", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_excel"}, {"name": "subSuite", "value": "TestExcel"}, {"name": "host", "value": "DESKTOP-T3GOI97"}, {"name": "thread", "value": "4384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_excel"}]}